name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.30.0
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - uses: actions/setup-python@master
        with:
          python-version: 3.x

      - name: Install deps
        run: npm i -g tslint typescript

      - name: Print deno version
        run: deno --version

      - name: Check format
        run: deno fmt --check **/*

      - name: Lint
        run: npx tslint **/*.ts

      - name: Run tests
        run: deno test -A -c tsconfig.json

      - name: Run Benchmarks
        run: python ./tools/benchmark.py

      - name: Post Benchmarks
        if: github.ref == 'refs/heads/test_ci' && github.repository == 'zhmushan/abc'
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone --depth 1 -b benchmarks https://${PAT}@github.com/zhmushan/abc.git benchmarks
          python ./tools/build_benchmark_jsons.py
          cd benchmarks
          git config user.email "zhmushan@qq.com"
          git config user.name "zhmushan"
          git add .
          git commit --message "Update benchmarks"
          git push origin benchmarks
